#version: '3.8'
services:

  #  startup:
  #  - goto http://localhost:3000/
  #  - Workspace ->
  #
  #  ollama pull phi3
  #  ollama pull llama3
  #
  #

  # ollama and API
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: missing
    tty: true
    restart: unless-stopped
    # Expose Ollama API outside the container stack
    ports:
      - "11434:11434"
    #  - "53:53"
    volumes:
      - ./ollama:/root/.ollama
    networks:
     - ollama-docker

    # GPU support (turn off by commenting with # if you don't have an nvidia gpu)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu

  # webui, navigate to http://localhost:3000/ to use
  # see: https://docs.openwebui.com/getting-started/
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: missing
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:  # see: https://docs.openwebui.com/getting-started/env-configuration
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - "WEBUI_AUTH=false"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
     - ollama-docker

networks:
 ollama-docker:
   external: false

# volumes:
#  ollama: {}
#  open-webui: {}
